Jsdocs
iad-os/nightswatch pull request #9
Opened 2020-03-02 11:38 UTC by fabioVRomano

add jsdocs

2020-03-02 15:39 UTC, ghost requested changes
Avete definito gli oggetti, ma poi non li avete mai utilizzati nelle varie definizioni, lasciando sempre Object

2020-03-02 15:39 UTC, nick23roma commented on src/conf.js
> + * @property {Object} targets
Manca da applicare le nuove tipizzazioni per Oggetto NightsWatchConfig

2020-03-02 15:39 UTC, nick23roma commented on src/conf.js
> +   * @property {Object} specs
Da cambiare il tipo di oggetto

2020-03-02 15:39 UTC, nick23roma commented on src/conf.js
> +    * @property {Object} http
Da cambiare il tipi di oggetto

2020-03-02 15:39 UTC, nick23roma commented on src/conf.js
> +    * @property {Object} healthchecks
Da cambiare il tipo di oggetto

2020-03-02 15:39 UTC, nick23roma commented on src/conf.js
> +     * @property {Object} oidc_paths
Da cambiare il tipo di oggetto

2020-03-03 09:07 UTC, danielefiungo approved these changes

2020-03-03 15:43 UTC, merged